### ISSUE TITLE
Limit Nagios monitoring to specified hostgroups?

### ISSUE THREAD

**Issue by westbywest** [tas50/nagios#295]
This cookbook's current behavior is to populate Nagios hostgroup entries for all roles found in the current environment (or in all environments if node['nagios']['multi_environment_monitoring'] is true).  This can make the Nagios web UI unwieldy, especially if one has many unused roles.

This behavior makes the nagios_hostgroups databag a bit redundant, and indeed the cookbook will throw an error if an item in that databag is a role that the cookbook already found by searching the Chef server.

Would it make sense to add a true/false option to control whether the cookbook will search all nodes for potential monitoring by Nagios, e.g. node['nagios']['specify_hostgroups'] ?  Setting this option to true would limit the search of nodes to be monitored to only those specified in nagios_hostgroups data bag items.

**Comment by roylindauer** [comment]
+1

**Comment by sbotman** [comment]
@westbywest since the change in the configuration model, you should be able to create any kind of logic you want for the configuration input. For example, you can disable the default_config or the databag loading by setting some attributes. And you can then apply your own logic within a separate recipe to load all the configuration items that you want. We at Schuberg Philis are doing this also and replaced the default_config with our own wrapper cookbook that does a partial search and only created configuration items based on the information that we specify on the partial search. Will close this issue because I feel that the current flexibility within the cookbook gives you enough options. But please feel free to open the issue again if you still have questions about this. Greeting Sander
